const RequestType = {
    LOGIN: "LOGIN REQ",
    OTP: "ONE_TIME_PASSOWORD REQ",
    PROFILE_INIT: "PROFILE INITIATION REQ",
    LLI: "LAST LOGIN INFO UPDATE REQ",
    LC: "LANGUAGE CHANGE REQ",
    MRU: "MEDICAL RECORD UPLOAD",
    MRR: "MEDICAL RECORD RETRIEVAL",
    PU: "PROFILE UPDATE",
    RDR: "RECORD DATA RETRIEVAL",
    AR: "AI RECOMMENDATION",
    SYM: "SYMPTOMS RETRIEVAL",
    IR: "INSTITUTION RETRIEVAL",
    SCHID: "SCHEDULE RETRIEVAL BY USERID",
};

module.exports = RequestType;
