const RequestType = {
    LOGIN: "LOGIN REQ",
    OTP: "ONE_TIME_PASSOWORD REQ",
    PROFILE_INIT: "PROFILE INITIATION REQ",
    LLI: "LAST LOGIN INFO UPDATE REQ",
    LC: "LANGUAGE CHANGE REQ",
    MRU: "MEDICAL RECORD UPLOAD",
    MRR: "MEDICAL RECORD RETRIEVAL",
};

module.exports = RequestType;
